# Generated by Django 4.0.4 on 2023-01-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_subuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubUser',
        ),
    ]
