# Generated by Django 4.0.4 on 2023-01-30 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_subuser_delete_hi_alter_project_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, default=5, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.subuser'),
        ),
    ]
