# Generated by Django 4.0.4 on 2023-01-30 12:39

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C/Users/User/Desktop/educational website project-assignment/projects_assignment/files/projects'), upload_to=''),
        ),
    ]
