# Generated by Django 4.0.4 on 2023-02-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_project_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='SubUser',
        ),
    ]
