# Generated by Django 4.0.4 on 2023-02-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_description_alter_project_project_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
