# Generated by Django 4.0.4 on 2023-02-19 21:23

import django.core.files.storage
from django.db import migrations
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_delete_userinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_file',
            field=projects.models.ProjectFileField(storage=django.core.files.storage.FileSystemStorage(location='files/projects'), upload_to=''),
        ),
    ]
