# Generated by Django 4.0.4 on 2023-07-21 14:11

import django.core.files.storage
from django.db import migrations
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_project_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_file',
            field=projects.models.ProjectFileField(storage=django.core.files.storage.FileSystemStorage(location='/home/mrAmrEmam/django-app/files/projects'), upload_to=''),
        ),
    ]
