# Generated by Django 4.0.4 on 2023-02-07 14:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_userinformation_bio_alter_userinformation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='cropped_profile_image',
            field=models.ImageField(default=1, storage=django.core.files.storage.FileSystemStorage(location='files/user_information/'), upload_to=''),
            preserve_default=False,
        ),
    ]
