# Generated by Django 4.0.4 on 2023-02-11 16:13

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0003_userinformation_cropped_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='cropped_profile_image',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='files/user_information/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='profile_image',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='files/user_information/'), upload_to=''),
        ),
    ]
