# Generated by Django 4.0.4 on 2023-02-12 20:11

import django.core.files.storage
from django.db import migrations
import user_authentication.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0006_alter_userinformation_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='cropped_profile_image',
            field=user_authentication.models.CroppedImageImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='files/user_information/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='profile_image',
            field=user_authentication.models.ProfileImageImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='files/user_information/'), upload_to=''),
        ),
    ]
