# Generated by Django 4.0.4 on 2023-02-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0007_alter_userinformation_cropped_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
