# Generated by Django 4.0.4 on 2023-07-17 16:43

import django.core.files.storage
from django.db import migrations
import user_authentication.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0008_alter_userinformation_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='cropped_profile_image',
            field=user_authentication.models.CroppedImageImageField(default='files/user_information/defaultprofileimage.jpg', storage=django.core.files.storage.FileSystemStorage(location='files/user_information/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='profile_image',
            field=user_authentication.models.ProfileImageImageField(default='files/user_information/defaultprofileimage.jpg', storage=django.core.files.storage.FileSystemStorage(location='files/user_information/'), upload_to=''),
        ),
    ]
