# Generated by Django 4.0.4 on 2023-07-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0009_alter_userinformation_bio_and_more'),
        ('user_authentication', '0010_alter_userinformation_cropped_profile_image'),
    ]

    operations = [
    ]
