# Generated by Django 4.0.4 on 2023-07-21 13:12

import django.core.files.storage
from django.db import migrations, models
import user_authentication.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0011_merge_20230718_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='cropped_profile_image',
            field=user_authentication.models.CroppedImageImageField(default='/home/mrAmrEmam/django-app/files/user_information/defaultcroppedprofile.jpg', storage=django.core.files.storage.FileSystemStorage(location='/home/mrAmrEmam/django-app/files/user_information'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='profile_image',
            field=user_authentication.models.ProfileImageImageField(default='/home/mrAmrEmam/django-app/files/user_information/defaultprofileimage.jpg', storage=django.core.files.storage.FileSystemStorage(location='/home/mrAmrEmam/django-app/files/user_information'), upload_to=''),
        ),
    ]
