# Generated by Django 4.0.4 on 2023-07-21 20:19

import django.core.files.storage
from django.db import migrations
import user_authentication.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0012_alter_userinformation_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='cropped_profile_image',
            field=user_authentication.models.CroppedImageImageField(default='C:\\Users\\User\\Desktop\\projects\\educational website project-assignment\\django-app\\files/user_information/defaultcroppedprofile.jpg', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\User\\Desktop\\projects\\educational website project-assignment\\django-app\\files/user_information'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='profile_image',
            field=user_authentication.models.ProfileImageImageField(default='C:\\Users\\User\\Desktop\\projects\\educational website project-assignment\\django-app\\files/user_information/defaultprofileimage.jpg', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\User\\Desktop\\projects\\educational website project-assignment\\django-app\\files/user_information'), upload_to=''),
        ),
    ]
