# Generated by Django 4.0.4 on 2023-03-26 12:13

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image_comment',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='files/reviews'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.review'),
        ),
    ]
