# Generated by Django 4.0.4 on 2023-04-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_pdf',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
