# Generated by Django 4.0.4 on 2023-07-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_review_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='general_comment',
            field=models.BooleanField(default=False),
        ),
    ]
