# Generated by Django 4.0.4 on 2023-07-09 14:38

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_comment_general_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image_comment',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='files/reviews'), upload_to=''),
        ),
    ]
