# Generated by Django 4.0.4 on 2023-07-21 14:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_comment_image_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image_comment',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home/mrAmrEmam/django-app/files/reviews'), upload_to=''),
        ),
    ]
